language: python

sudo: false

env:
  matrix:
    - VLUA="lua=5.4"
    - VLUA="lua=5.3"
    - VLUA="lua=5.2"
    - VLUA="lua=5.1"
    - VLUA="luajit=2.1"
    - VLUA="luajit=2.0"


before_install:
  - pip install hererocks
  - hererocks here --luarocks 3 --$VLUA
  - export PATH=$PWD/here/bin:$PATH

  - hererocks tools --luajit=2.0
  - export PATH=$PATH:$PWD/tools/bin


install:
  - luarocks --lua-dir=$PWD/tools --tree=$PWD/tools install ldoc
  - luarocks --lua-dir=$PWD/tools --tree=$PWD/tools install ansicolors
  - luarocks --lua-dir=$PWD/tools --tree=$PWD/tools install specl
  - luarocks --lua-dir=$PWD/tools --tree=$PWD/tools install luacov
  # luarocks install typecheck

script:
  - luarocks make --force LUA_INCDIR=$PWD/here/include
  - specl -vfreport --coverage spec/*_spec.yaml

after_success:
  - bash <(curl -s https://codecov.io/bash) -f luacov.report.out

notifications:
  slack: aspirinc:JyWeNrIdS0J5nf2Pn2BS1cih
